apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "sticky.fullname" . }}-secrets
stringData:
  {{- if .Values.secrets.apiKeys }}
  api_keys: {{ .Values.secrets.apiKeys | quote }}
  {{- end }}
  {{- if .Values.secrets.fernetKey }}
  fernet.key: {{ .Values.secrets.fernetKey | quote }}
  {{- end }}
  {{- if .Values.secrets.registrationToken }}
  registration.token: {{ .Values.secrets.registrationToken | quote }}
  {{- end }}