apiVersion: v1
kind: Service
metadata:
  name: {{ include "sticky.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "sticky.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: {{ .Values.service.metricsPort }}